In [2]:
import numpy as np
#Arithmatic operations
arr1 = np.arange(4,dtype = np.float_).reshape(2,2)
print("First array")
print(arr1)
print("Second array:")
arr2=np.array([12,13])
print(arr2)
print("Adding the two arrays:")
print(np.add(arr1,arr2))
print("Substracting the two arrays:")
print(np.subtract(arr1,arr2))
print("Multiplying the two arrays:")
print(np.multiply(arr1,arr2))
print("Dividing the two arrays:")
print(np.divide(arr1,arr2))

First array
[[0. 1.]
 [2. 3.]]
Second array:
[12 13]
Adding the two arrays:
[[12. 14.]
 [14. 16.]]
Substracting the two arrays:
[[-12. -12.]
 [-10. -10.]]
Multiplying the two arrays:
[[ 0. 13.]
 [24. 39.]]
Dividing the two arrays:
[[0.         0.07692308]
 [0.16666667 0.23076923]]


In [4]:
#numpy reciprocal
arr3=np.array([25,1.33,1,1,100])
print("Array is:")
print(arr3)
print("After applying reciprocal function array is:")
print(np.reciprocal(arr3))

Array is:
[ 25.     1.33   1.     1.   100.  ]
After applying reciprocal function array is:
[0.04      0.7518797 1.        1.        0.01     ]


In [16]:
#numpy power
import numpy as np
arr=np.array([5,10,15,20])
print("First array is:")
print(arr)
print("After applying power function array is:")
print(np.power(arr,2))




First array is:
[ 5 10 15 20]
After applying power function array is:
[ 25 100 225 400]


In [8]:
#mod function
arr5=np.array([5,15,20])
print("First Array is:")
print(arr5)

arr6=np.array([2,5,9])
print("Second Array is:")
print(arr6)

print("Applying mod function :")
print(np.mod(arr5,arr6))

print("Applying reminder function :")
print(np.remainder(arr5,arr6))

First Array is:
[ 5 15 20]
Second Array is:
[2 5 9]
Applying mod function :
[1 0 2]
Applying reminder function :
[1 0 2]


In [21]:
#index
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [25]:
#slicing
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [29]:
#datatypes
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [33]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)


<U6


In [37]:

#2-d shape import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [39]:
#1-d to 2-d
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
#1-D to 3-D
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [45]:
#join two arrays
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [47]:
#join two 2-D arrays
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [49]:
#Split the array in 3 parts:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
